apiVersion: apps/v1
kind: Deployment
metadata:
  name: techtrends-latest
  namespace: sandbox
  labels:
    app: techtrends
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techtrends
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
      - name: techtrends
        imagePullPolicy: IfNotPresent
        image: nikwhittington/techtrends:latest
        ports:
        - containerPort: 3111
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3111
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3111
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 250m
            memory: 64Mi